#!/bin/sh

# [Toot] in the comfort of your shell and/or favorite editor
# This is forked from jn: https://github.com/CosineP/jn
# License GPLv3

toot() {
  echo $1 | toot.py &
}

if [ "$1" = "" ]; then

  # Set up the file with nothing
  > /tmp/fd
  # The user edits the toot in their editor
  # These are vim-only commands to start at the end, in insert mode
  $EDITOR -c 'startinsert' + /tmp/fd
  new="$(cat /tmp/fd)"

  if [ -z "$new" ]; then
    echo "File unchanged, not tooting"
  else
    toot "$(cat /tmp/fd)"
  fi

else

  # You can specify exactly what to add to fd in a one-liner by just adding it
  toot "$*"

fi

